# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Artist.create(name: "Aaa")
Artist.create(name: "Aaba")
Artist.create(name: "Abaa")
Artist.create(name: "Abbaa")
Artist.create(name: "Abbbaa")
Artist.create(name: "Acaa")
Artist.create(name: "ccaa")
Artist.create(name: "cccccccaa")
Artist.create(name: "Ccccccaacccccaa")
Artist.create(name: "Vcccccaacccccaa")
Artist.create(name: "Ncccccaacccccaa")
Artist.create(name: "Dcccccaacccccaa")
Artist.create(name: "vvvvaa")
Artist.create(name: "Evvvvaa")
Artist.create(name: "vaa")
Artist.create(name: "Fvaa")
Artist.create(name: "vvaa")
Artist.create(name: "Gvvaa")
Artist.create(name: "naa")
Artist.create(name: "Hnaa")
Artist.create(name: "nnaa")
Artist.create(name: "nnnnaa")
Song.create(title: "alongside", artist_id: 1)
Song.create(title: "aeee", artist_id: 2)
Song.create(title: "aeefg", artist_id: 1)
Song.create(title: "bba", artist_id: 1)
Song.create(title: "bbbba", artist_id: 1)
Song.create(title: "babb", artist_id: 1)
Song.create(title: "cccca", artist_id: 3)
Song.create(title: "gggga", artist_id: 1)
Song.create(title: "rrra", artist_id: 1)
Song.create(title: "jkla", artist_id: 1)
Song.create(title: "wa", artist_id: 1)
Song.create(title: "wwa", artist_id: 4)
Song.create(title: "wwwwa", artist_id: 5)
Song.create(title: "wwwwwa", artist_id: 1)
Song.create(title: "wwwwwwwwa", artist_id: 11)
Song.create(title: "wweeea", artist_id: 11)
Song.create(title: "fgha", artist_id: 11)
Song.create(title: "avvvv", artist_id: 12)
Song.create(title: "abbbbggg", artist_id: 12)
Song.create(title: "ajjkk", artist_id: 12)
Song.create(title: "aklo", artist_id: 13)
Song.create(title: "afgrty", artist_id: 13)
Download.create(song_id: 1)
Download.create(song_id: 1)
Download.create(song_id: 1)
Download.create(song_id: 1)
Download.create(song_id: 1)
Download.create(song_id: 1)
Download.create(song_id: 1)
Download.create(song_id: 1)
Download.create(song_id: 1)
Download.create(song_id: 1)
Download.create(song_id: 1)
Download.create(song_id: 2)
Download.create(song_id: 2)
Download.create(song_id: 2)
Download.create(song_id: 2)
Download.create(song_id: 2)
Download.create(song_id: 2)
Download.create(song_id: 2)
Download.create(song_id: 3)
Download.create(song_id: 4)
Download.create(song_id: 4)
Download.create(song_id: 4)
Download.create(song_id: 4)
Download.create(song_id: 4)
Download.create(song_id: 4)
Download.create(song_id: 4)
Download.create(song_id: 4)
Download.create(song_id: 4)
Download.create(song_id: 5)
Download.create(song_id: 5)
Download.create(song_id: 5)
Download.create(song_id: 5)
Download.create(song_id: 5)
Download.create(song_id: 5)
Download.create(song_id: 5)
Download.create(song_id: 5)
Download.create(song_id: 5)
Download.create(song_id: 5)
Download.create(song_id: 5)
Download.create(song_id: 5)
Download.create(song_id: 5)
Download.create(song_id: 5)
Download.create(song_id: 5)
Download.create(song_id: 5)
Download.create(song_id: 6)
Download.create(song_id: 6)
Download.create(song_id: 6)
Download.create(song_id: 6)
Download.create(song_id: 6)
Download.create(song_id: 6)
Download.create(song_id: 7)
Download.create(song_id: 7)
Download.create(song_id: 7)
Download.create(song_id: 7)
Download.create(song_id: 7)
Download.create(song_id: 7)
Download.create(song_id: 7)
Download.create(song_id: 7)
Download.create(song_id: 7)
Download.create(song_id: 7)
Download.create(song_id: 7)
Download.create(song_id: 7)
Download.create(song_id: 7)
Download.create(song_id: 8)
Download.create(song_id: 8)
Download.create(song_id: 8)
Download.create(song_id: 8)
Download.create(song_id: 8)
Download.create(song_id: 8)
Download.create(song_id: 8)
Download.create(song_id: 8)
Download.create(song_id: 8)
Download.create(song_id: 8)
Download.create(song_id: 8)
Download.create(song_id: 9)
Download.create(song_id: 9)
Download.create(song_id: 9)
Download.create(song_id: 9)
Download.create(song_id: 9)
Download.create(song_id: 9)
Download.create(song_id: 9)
Download.create(song_id: 10)
Download.create(song_id: 10)
Download.create(song_id: 10)
Download.create(song_id: 10)
Download.create(song_id: 10)
Download.create(song_id: 10)
Download.create(song_id: 11)
Download.create(song_id: 11)
Download.create(song_id: 11)
Download.create(song_id: 11)
Download.create(song_id: 11)
Download.create(song_id: 11)
Download.create(song_id: 11)
Download.create(song_id: 11)
Download.create(song_id: 11)
Download.create(song_id: 11)
Download.create(song_id: 11)
Download.create(song_id: 12)
Download.create(song_id: 12)
Download.create(song_id: 12)
Download.create(song_id: 12)
Download.create(song_id: 13)
Download.create(song_id: 13)
Download.create(song_id: 13)
Download.create(song_id: 13)
Download.create(song_id: 13)
Download.create(song_id: 14)
Download.create(song_id: 14)
Download.create(song_id: 14)
Download.create(song_id: 14)
Download.create(song_id: 14)
Download.create(song_id: 14)
Download.create(song_id: 15)
Download.create(song_id: 15)
Download.create(song_id: 15)
Download.create(song_id: 15)
Download.create(song_id: 15)
